# Generated by Django 5.0.3 on 2024-11-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
